// <auto-generated>
// SimHub External Game telemetry sender (C#) - Pack=1 structs
// Generated by SimHub CSharpGenerator
// </auto-generated>

using System;
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.IO;

namespace SimHubExternalTelemetrySender
{
    public static class SHTelemetryConstants
    {
        public const string DefinitionUniqueId = "9a62309a-8a8d-4ad1-b711-637361b844a8";
        public const uint GameSignature = 0x51963903u;
        public const uint TelemetrySignature = 0x8A3F0EE7u;

        public const ushort LayoutMajorVersion = 1;
        public const ushort LayoutMinorVersion = 0;

        public const int ExpectedPacketLength = 101;

        public const string DefaultHost = "127.0.0.1";
        public const int DefaultPort = 35353;
    }

    public static class SHTelemetryHelpers
    {
        // ------------------------------------------------------------------------------------
        // Definition registration
        // ------------------------------------------------------------------------------------
        // To make SimHub detect your telemetry definition, you must register the Definition file.
        //
        // This is done by creating a file:
        //   %LocalAppData%\SimHub\ExternalSims\Registrations\{DefinitionUniqueId}.simlink
        //
        // The file must contain a single line: the full path to your definition (.simdef).
        //
        // Example:
        //   SHTelemetryHelpers.RegisterDefinition("C:\\MyGame\\telemetry.simdef");
        //
        // Notes:
        // - The filename MUST match the DefinitionUniqueId
        // - The path should ideally be absolute
        // - Safe to call at every startup (recommended)
        // - The file is always rewritten to keep the path valid if the game is moved
        // ------------------------------------------------------------------------------------
        public static bool RegisterDefinition(string definitionPath, bool makeAbsolute = true)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(definitionPath))
                    throw new ArgumentNullException(nameof(definitionPath));

                string finalPath = definitionPath.Trim();

                if (makeAbsolute)
                {
                    finalPath = Path.GetFullPath(finalPath);
                }

                string baseDir = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                    "SimHub",
                    "ExternalSims",
                    "Registrations");

                Directory.CreateDirectory(baseDir);

                string linkFile = Path.Combine(
                    baseDir,
                    SHTelemetryConstants.DefinitionUniqueId + ".simlink");

                // Always rewrite → self-healing if path changed
                File.WriteAllText(linkFile, finalPath);

                Console.WriteLine($"Definition registered: {linkFile} -> {finalPath}");
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to register definition: {ex.Message}");
                return false;
            }
        }

        public static void WriteUtf8Z(byte[] dest, string value)
        {
            Array.Clear(dest, 0, dest.Length);
            if (string.IsNullOrEmpty(value)) return;

            var bytes = Encoding.UTF8.GetBytes(value);
            int n = bytes.Length;
            if (n >= dest.Length) n = dest.Length - 1; // keep room for NUL
            Buffer.BlockCopy(bytes, 0, dest, 0, n);
            dest[n] = 0;
        }

        public static ulong CreateRandomUInt64()
        {
            var b = Guid.NewGuid().ToByteArray();
            return BitConverter.ToUInt64(b, 0);
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct SHTelemetryPacket
    {
        // Header
        // Game signature : Stable identity of the game. Must match the definition GameSignature.
        public uint GameSignature;

        // Telemetry signature : Schema/protocol identity (includes game identity and telemetry layout). Must match the expected signature.
        public uint TelemetrySignature;

        // Major layout version : Increment at every breaking change (Fields removal, fields reordering).
        public ushort LayoutMajorVersion;

        // Minor layout version : Increment at every minor change (Only fields append).
        public ushort LayoutMinorVersion;

        // Emitter instance ID : Unique identifier of the telemetry emitter instance. Must be generated once at emitter startup and remain constant for the lifetime of the process or telemetry session. Used to distinguish multiple concurrent emitters and avoid mixing data streams. Should be non-zero when possible.
        public ulong EmitterInstanceId;

        // Packet type Id : Packet type identifier. Currently always 0. Reserved for future extension (e.g. multiple packet types or partial updates).
        public byte PacketId;

        // Packet counter : Monotonic increasing counter incremented for every packet sent. Must not reset during a session. Used to detect packet loss, duplication, or reordering. Packets should continue to be emitted even when the game is paused.
        public ulong PacketsCounter;

        // Session running flag : 1 if a session is currently active, 0 otherwise.
        public byte IsSessionRunning;

        // Session paused flag : 1 if the current session is paused, 0 otherwise.
        public byte IsSessionPaused;

        // Session unique ID : Unique identifier of the current session. Changes when a new session starts or restarts. Can be a random 64-bit integer.
        public ulong SessionId;

        // Replay mode flag : 1 if the telemetry is coming from replayed data rather than live gameplay. When set, consumers may choose to disable real-time features such as motion or haptics, but all telemetry fields should otherwise remain valid and consistent with normal playback.
        public byte IsReplay;

        // User in control flag : 1 if the user is currently in control, 0 otherwise.
        public byte IsUserInControl;

        // AI in control flag : 1 if the AI is currently in control of the user's vehicle. Can be combined with IsUserInControl during assisted drivings (pit entry, pit exit etc ...)
        public byte IsAIInControl;

        // Spectator mode flag : 1 if the user is spectating rather than actively participating. Telemetry remains valid, but may not represent a player-controlled vehicle.
        public byte IsSpectator;

        // Session time (seconds) : Accurate session time in seconds. Intended for physics computations and precise timing.  May reset when SessionId changes.
        public double SessionTimeSeconds;

        // Physics discontinuity counter : Incremented once each time a discontinuity occurs where physics continuity may be broken (teleportation, AI control switch, replay rewind/seek, etc.). Used to detect abrupt changes and allow consumers (e.g. motion systems) to reset or smooth transitions. Must remain constant otherwise. May increment together with a SessionId change.
        public uint PhysicsDiscontinuityCounter;


        // Fields
        // Vehicle speed (km/h) : Vehicle speed in km/h (as reported by the HUD including wheels spin etc ...)
        public float SpeedKmh;

        // Engine Ignition on flag : Engine ignition status flag (0 off, 1 on)
        public byte EngineIgnitionOn;

        // Engine started : Engine is started status flag (0 off, 1 on)
        public byte EngineStarted;

        // Engine RPM : Current engine revolutions per minute
        public float EngineRpm;

        // Max RPM : Maximum engine RPM
        public float EngineMaxRpm;

        // Throttle input : Throttle pedal position (0-1)
        public float Throttle;

        // Gear : Current gear as text (R,N,1..N)
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] 
        public byte[] Gear; // UTF8Z(8)

        // Max gears : Maximum number of gears
        public int MaxGears;

        // Fuel level : Remaining fuel amount (Liters)
        public float Fuel;

        // Max fuel : Maximum fuel capacity (Liters)
        public float MaxFuel;

        // Oil temperature : Engine oil temperature (°C)
        public float OilTemperature;

        // Water temperature : Engine coolant temperature (°C)
        public float WaterTemperature;

        public static SHTelemetryPacket CreateDefault()
        {
            var p = new SHTelemetryPacket();

            p.GameSignature = SHTelemetryConstants.GameSignature;
            p.TelemetrySignature = SHTelemetryConstants.TelemetrySignature;

            p.LayoutMajorVersion = SHTelemetryConstants.LayoutMajorVersion;
            p.LayoutMinorVersion = SHTelemetryConstants.LayoutMinorVersion;

            p.Gear = new byte[8];
            return p;
        }

        public void Set_Gear(string value) => SHTelemetryHelpers.WriteUtf8Z(this.Gear, value);

    }

    public static class Program
    {
        public static void Main(string[] args)
        {

            // ------------------------------------------------------------------------------------
            // Definition registration
            // ------------------------------------------------------------------------------------
            // Once your telemetry definition (.simdef) is created, it should be stored alongside
            // your simulation files.
            //
            // At simulation startup, register the definition so it can be discovered.
            // This call is safe to perform at every startup (the link file is always updated).
            //
            // Example:
            // SHTelemetryHelpers.RegisterDefinition("C:\\Path\\To\\Your\\definition.simdef");
            // ------------------------------------------------------------------------------------

            // Host and port should be configurable in your application (UI),
            // but also stored in a simple, externally editable configuration file.
            // This allows external tools to inspect and adjust the configuration if needed.
            string host = SHTelemetryConstants.DefaultHost;
            int port = SHTelemetryConstants.DefaultPort;

            var endPoint = new IPEndPoint(IPAddress.Parse(host), port);
            using (var udp = new UdpClient())
            {
                udp.Connect(endPoint);

                var packet = SHTelemetryPacket.CreateDefault();
                int size = Marshal.SizeOf(typeof(SHTelemetryPacket));

                // Emitter instance : Fixed per process
                var emitterInstanceId = SHTelemetryHelpers.CreateRandomUInt64(); 
                packet.EmitterInstanceId = emitterInstanceId;

                // Set a session ID and mark it as running and user in control, the session id must be renewed for every new session in the game
                var sessionId = SHTelemetryHelpers.CreateRandomUInt64(); 
                packet.SessionId = sessionId;
                packet.IsSessionRunning = 1;
                packet.IsUserInControl = 1;
                packet.IsSessionPaused = 0;
                packet.SessionTimeSeconds = 0.0;

                if (SHTelemetryConstants.ExpectedPacketLength > 0 && size != SHTelemetryConstants.ExpectedPacketLength)
                {
                    Console.WriteLine($"WARNING: Struct size {size} != ExpectedPacketLength {SHTelemetryConstants.ExpectedPacketLength}");
                }

                byte[] buffer = new byte[size];
                IntPtr ptr = Marshal.AllocHGlobal(size);

                try
                {
                    Console.WriteLine($"Sending {size} bytes @60Hz to {endPoint} (GameSig=0x{SHTelemetryConstants.GameSignature:X8}, TelemetrySig=0x{SHTelemetryConstants.TelemetrySignature:X8})");

                    var sw = Stopwatch.StartNew();
                    double last = 0.0;

                    while (true)
                    {
                        double now = sw.Elapsed.TotalSeconds;
                        double dt = now - last;
                        if (dt < 0) dt = 0;
                        last = now;

                        // Increment packet time
                        packet.SessionTimeSeconds += dt;

                        // Increment packet counter
                        packet.PacketsCounter += 1;

                        Marshal.StructureToPtr(packet, ptr, false);
                        Marshal.Copy(ptr, buffer, 0, size);
                        udp.Send(buffer, buffer.Length);

                        Thread.Sleep(15);
                    }
                }
                finally
                {
                    Marshal.FreeHGlobal(ptr);
                }
            }
        }
    }
}
